type: web
name: tg-openai-bot
env: python
plan: free
buildCommand: pip install -r requirements.txt
startCommand: python main.py
envVars:
  - key: BOT_TOKEN
    value: <ТВОЙ_ТОКЕН>
  - key: OPENAI_API_KEY
    value: <ТВОЙ_OPENAI_API_KEY>
